
package com.re01.myclient.server_package;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.9
 * 2019-07-30T09:29:22.282+08:00
 * Generated source version: 3.2.9
 *
 */
public final class IMyServer_MyServerImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.jh.re01.com/", "MyServer");

    private IMyServer_MyServerImplPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = MyServer.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        MyServer ss = new MyServer(wsdlURL, SERVICE_NAME);
        IMyServer port = ss.getMyServerImplPort();

        {
        System.out.println("Invoking sendInfo...");
        String _sendInfo__return = port.sendInfo();
        System.out.println("sendInfo.result=" + _sendInfo__return);


        }

        System.exit(0);
    }

}
